---
- name: Update/Upgrade apt archives
  ansible.builtin.apt:
    update_cache: yes
    upgrade: "yes"
  become: yes
  
- name: Install packages on private hosts
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}" 
  become: yes
