---
- name: Copy nginx config file
  ansible.builtin.copy:
    src: ../files/linux-training.conf
    dest: /etc/nginx/conf.d/linux-training.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Restart nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: yes
