---
# tasks file for linux-training

- name: Add linux user
  ansible.builtin.include_tasks: add_linux_user.yml
  when:
    - add_linux_user

- name: Add user to sudo group
  ansible.builtin.include_tasks: add_user_sudo.yml
  when:
    - add_user_sudo

- name: Install OTEL collector
  ansible.builtin.include_tasks: install_otel_collector.yml
  when:
    - install_otel_collector

